### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [lifetimetraveler/cpp202309#1]
### 없는 파일
- challenge/week2/candy.cpp 
- challenge/week2/temperature.cpp 
- challenge/week2/temperature2.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

**Comment by lifetimetraveler** [comment]
당시에 practice만 하라고 하셔서 파일이 없었습니다. 방금 만들어서 업로드하였고, temperature2는 당시에 제가 집에가서 하고 challenge에 올리라고 되어있어서, challenge 폴더에 올렸습니다. 
파일을 week2에 올렸습니다. temperature2.cpp는 제가 그때 당시에 했던 것을 재업로드하였고, candy.cpp와 temperature.cpp는 방금 만들어서 올렸습니다.
항상 부족하지만 열심히 따라 가보도록 하겠습니다. 항상 열정적으로 강의해주셔서 더 수월하게 따라갈 수 있는 것 같습니다.

**Comment by MisooKim2** [comment]
네 고생하셨습니다.
이슈를 해결하신 이후에는 close 하시면 됩니다.
저 또한 부족함이 많은 강의를 잘 따라와주셔서 감사드립니다.
